name: TwitchWhitelist
version: 1.3
main: de.jakkoble.TwitchWhitelist
api-version: 1.16
authors: [ Jakkoble ]
description: Whitelist Players via Twitch Channel Points Reward
website: https://jakkoble.de